name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
webview_flutter: any
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  avatar_glow: 2.0.2
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: 1.5.1
  firebase_auth: ^4.1.5
  firebase_core: 2.4.0
  firebase_database: 10.0.6
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutterfire_cli: ^0.2.7
  get: 4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  lottie: ^2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
  uses-material-design: true
