name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  lottie: ^2.0.0
  introduction_screen: ^3.1.1
  avatar_glow: ^2.0.2
  emoji_picker_flutter: ^1.5.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  image_picker: ^0.8.6
  flutter_launcher_icons: ^0.11.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

